<?xml version="1.0" encoding="utf-8"?><Database Name="PiggyBank" Class="ConexionLINQDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=34.41.22.76;Initial Catalog=PiggyBank;Persist Security Info=True;User ID=PBADM_FABRI;Encrypt=True;Trust Server Certificate=True" SettingsObjectName="AccesoADatos.Properties.Settings" SettingsPropertyName="PiggyBankConnectionString6" Provider="System.Data.SqlClient" />
  <Function Name="dbo.SP_BALANCE_OBTENER_POR_GRUPO" Method="SP_BALANCE_OBTENER_POR_GRUPO">
    <Parameter Name="GrupoID" Parameter="grupoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FechaInicio" Parameter="fechaInicio" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaFin" Parameter="fechaFin" Type="System.DateTime" DbType="Date" />
    <ElementType Name="SP_BALANCE_OBTENER_POR_GRUPOResult">
      <Column Name="BalanceID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GrupoID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UsuarioID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NombreUsuario" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="TotalGastos" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="TotalPagado" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="Saldo" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="FechaCalculo" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_CERRAR_SESION" Method="SP_CERRAR_SESION">
    <Parameter Name="SesionID" Parameter="sesionID" Type="System.Int32" DbType="Int" />
    <Parameter Name="MotivoRevocacion" Parameter="motivoRevocacion" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_CHAT_ACTUALIZAR_RESPUESTA" Method="SP_CHAT_ACTUALIZAR_RESPUESTA">
    <Parameter Name="ChatID" Parameter="chatID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Respuesta" Parameter="respuesta" Type="System.String" DbType="Text" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_CHAT_REGISTRAR_CONSULTA" Method="SP_CHAT_REGISTRAR_CONSULTA">
    <Parameter Name="UsuarioID" Parameter="usuarioID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Consulta" Parameter="consulta" Type="System.String" DbType="Text" />
    <Parameter Name="ContextoJSON" Parameter="contextoJSON" Type="System.String" DbType="Text" />
    <Parameter Name="ChatID" Parameter="chatID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_GRUPO_INVITAR_MIEMBRO" Method="SP_GRUPO_INVITAR_MIEMBRO">
    <Parameter Name="GrupoID" Parameter="grupoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UsuarioID" Parameter="usuarioID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Rol" Parameter="rol" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_INGRESAR_USUARIO" Method="SP_INGRESAR_USUARIO">
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="CorreoElectronico" Parameter="correoElectronico" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="LlaveUnica" Parameter="llaveUnica" Type="System.String" DbType="VarChar(128)" />
    <Parameter Name="PasswordHash" Parameter="passwordHash" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="CodigoVerificacion" Parameter="codigoVerificacion" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="UsuarioID" Parameter="usuarioID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORMSGBD" Parameter="eRRORMSGBD" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_META_ACTUALIZAR_PROGRESO" Method="SP_META_ACTUALIZAR_PROGRESO">
    <Parameter Name="MetaID" Parameter="metaID" Type="System.Int32" DbType="Int" />
    <Parameter Name="MontoActual" Parameter="montoActual" Type="System.Decimal" DbType="Decimal(10,2)" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_META_CREAR" Method="SP_META_CREAR">
    <Parameter Name="UsuarioID" Parameter="usuarioID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="MontoObjetivo" Parameter="montoObjetivo" Type="System.Decimal" DbType="Decimal(10,2)" />
    <Parameter Name="FechaInicio" Parameter="fechaInicio" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaObjetivo" Parameter="fechaObjetivo" Type="System.DateTime" DbType="Date" />
    <Parameter Name="MetaID" Parameter="metaID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_OBTENER_TODOS_USUARIOS" Method="SP_OBTENER_TODOS_USUARIOS">
    <ElementType Name="SP_OBTENER_TODOS_USUARIOSResult">
      <Column Name="UsuarioID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="FechaRegistro" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UltimoAcceso" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_PRESUPUESTO_CREAR" Method="SP_PRESUPUESTO_CREAR">
    <Parameter Name="UsuarioID" Parameter="usuarioID" Type="System.Int32" DbType="Int" />
    <Parameter Name="CategoriaID" Parameter="categoriaID" Type="System.Int32" DbType="Int" />
    <Parameter Name="MontoLimite" Parameter="montoLimite" Type="System.Decimal" DbType="Decimal(10,2)" />
    <Parameter Name="Periodo" Parameter="periodo" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="FechaInicio" Parameter="fechaInicio" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaFin" Parameter="fechaFin" Type="System.DateTime" DbType="Date" />
    <Parameter Name="PresupuestoID" Parameter="presupuestoID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_PRESUPUESTO_OBTENER_RESUMEN" Method="SP_PRESUPUESTO_OBTENER_RESUMEN">
    <Parameter Name="UsuarioID" Parameter="usuarioID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FechaInicio" Parameter="fechaInicio" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaFin" Parameter="fechaFin" Type="System.DateTime" DbType="Date" />
    <ElementType Name="SP_PRESUPUESTO_OBTENER_RESUMENResult">
      <Column Name="PresupuestoID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Categoria" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MontoLimite" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="GastosActuales" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="Diferencia" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_REENVIAR_CODIGO_VERIFICACION" Method="SP_REENVIAR_CODIGO_VERIFICACION">
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="NuevoCodigo" Parameter="nuevoCodigo" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="MinutosValidez" Parameter="minutosValidez" Type="System.Int32" DbType="Int" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORMSG" Parameter="eRRORMSG" Type="System.String" DbType="VarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_TRANSACCION_REGISTRAR" Method="SP_TRANSACCION_REGISTRAR">
    <Parameter Name="UsuarioID" Parameter="usuarioID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Tipo" Parameter="tipo" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Monto" Parameter="monto" Type="System.Decimal" DbType="Decimal(10,2)" />
    <Parameter Name="CategoriaID" Parameter="categoriaID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Fecha" Parameter="fecha" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="Text" />
    <Parameter Name="EsCompartido" Parameter="esCompartido" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="GrupoID" Parameter="grupoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="TransaccionID" Parameter="transaccionID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_TRANSACCIONES_OBTENER_POR_USUARIO" Method="SP_TRANSACCIONES_OBTENER_POR_USUARIO">
    <Parameter Name="UsuarioID" Parameter="usuarioID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FechaInicio" Parameter="fechaInicio" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaFin" Parameter="fechaFin" Type="System.DateTime" DbType="Date" />
    <Parameter Name="Tipo" Parameter="tipo" Type="System.String" DbType="VarChar(10)" />
    <ElementType Name="SP_TRANSACCIONES_OBTENER_POR_USUARIOResult">
      <Column Name="TransaccionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Tipo" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Monto" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="Fecha" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Categoria" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Icono" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ColorHex" Type="System.String" DbType="VarChar(7)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_USUARIO_ACTUALIZAR_PERFIL" Method="SP_USUARIO_ACTUALIZAR_PERFIL">
    <Parameter Name="UsuarioID" Parameter="usuarioID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="ConfiguracionNotificaciones" Parameter="configuracionNotificaciones" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_USUARIO_CAMBIAR_PASSWORD" Method="SP_USUARIO_CAMBIAR_PASSWORD">
    <Parameter Name="UsuarioID" Parameter="usuarioID" Type="System.Int32" DbType="Int" />
    <Parameter Name="NuevoPasswordHash" Parameter="nuevoPasswordHash" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_BALANCE_CALCULAR_REGISTRAR" Method="SP_BALANCE_CALCULAR_REGISTRAR">
    <Parameter Name="GrupoID" Parameter="grupoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FechaInicio" Parameter="fechaInicio" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaFin" Parameter="fechaFin" Type="System.DateTime" DbType="Date" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <ElementType Name="SP_BALANCE_CALCULAR_REGISTRARResult">
      <Column Name="GrupoID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UsuarioID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TotalGastos" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="TotalPagado" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="Saldo" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="FechaCalculo" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_OBTENER_USUARIO_POR_ID" Method="SP_OBTENER_USUARIO_POR_ID">
    <Parameter Name="UsuarioID" Parameter="usuarioID" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_OBTENER_USUARIO_POR_IDResult">
      <Column Name="UsuarioID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="FechaRegistro" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UltimoAcceso" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ConfiguracionNotificaciones" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="LlaveUnica" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordHash" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_ACTUALIZAR_ULTIMO_ACCESO" Method="SP_ACTUALIZAR_ULTIMO_ACCESO">
    <Parameter Name="UsuarioID" Parameter="usuarioID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_OBTENER_USUARIO_POR_EMAIL" Method="SP_OBTENER_USUARIO_POR_EMAIL">
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <ElementType Name="SP_OBTENER_USUARIO_POR_EMAILResult">
      <Column Name="UsuarioID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="FechaRegistro" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UltimoAcceso" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ConfiguracionNotificaciones" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="PasswordHash" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="LlaveUnica" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="EmailVerificado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_GASTO_COMPARTIDO_REGISTRAR" Method="SP_GASTO_COMPARTIDO_REGISTRAR">
    <Parameter Name="GrupoID" Parameter="grupoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UsuarioID" Parameter="usuarioID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Monto" Parameter="monto" Type="System.Decimal" DbType="Decimal(10,2)" />
    <Parameter Name="Estado" Parameter="estado" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="CategoriaID" Parameter="categoriaID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="Text" />
    <Parameter Name="GastoID" Parameter="gastoID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="TransaccionID" Parameter="transaccionID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_ABRIR_SESION" Method="SP_ABRIR_SESION">
    <Parameter Name="UsuarioID" Parameter="usuarioID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Guid" Parameter="guid" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="FechaExpiracion" Parameter="fechaExpiracion" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="SesionID" Parameter="sesionID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_ACTUALIZAR_TOKEN_SESION" Method="SP_ACTUALIZAR_TOKEN_SESION">
    <Parameter Name="SesionID" Parameter="sesionID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Guid" Parameter="guid" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_ACTIVAR_USUARIO" Method="SP_ACTIVAR_USUARIO">
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="CodigoVerificacion" Parameter="codigoVerificacion" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORMSG" Parameter="eRRORMSG" Type="System.String" DbType="VarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_SESION_OBTENER_POR_GUID" Method="SP_SESION_OBTENER_POR_GUID">
    <Parameter Name="Guid" Parameter="guid" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="ErrorID" Parameter="errorID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ErrorMensaje" Parameter="errorMensaje" Type="System.String" DbType="VarChar(255)" Direction="InOut" />
    <ElementType Name="SP_SESION_OBTENER_POR_GUIDResult">
      <Column Name="SesionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UsuarioID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Guid" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="FechaCreacion" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FechaExpiracion" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EsActivo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MotivoRevocacion" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_GRUPO_SALIR_MIEMBRO" Method="SP_GRUPO_SALIR_MIEMBRO">
    <Parameter Name="GrupoID" Parameter="grupoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UsuarioID" Parameter="usuarioID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_GRUPO_CREAR" Method="SP_GRUPO_CREAR">
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="Text" />
    <Parameter Name="UsuarioID" Parameter="usuarioID" Type="System.Int32" DbType="Int" />
    <Parameter Name="GrupoID" Parameter="grupoID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_GRUPO_LISTAR_POR_USUARIO" Method="SP_GRUPO_LISTAR_POR_USUARIO">
    <Parameter Name="UsuarioID" Parameter="usuarioID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <ElementType Name="SP_GRUPO_LISTAR_POR_USUARIOResult">
      <Column Name="GrupoID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="FechaCreacion" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreadoPorUsuarioID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="FechaActualizacion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Rol" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_GRUPO_ELIMINAR_MIEMBRO" Method="SP_GRUPO_ELIMINAR_MIEMBRO">
    <Parameter Name="GrupoID" Parameter="grupoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UsuarioID" Parameter="usuarioID" Type="System.Int32" DbType="Int" />
    <Parameter Name="AdminUsuarioID" Parameter="adminUsuarioID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_GRUPO_ACTUALIZAR" Method="SP_GRUPO_ACTUALIZAR">
    <Parameter Name="GrupoID" Parameter="grupoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="Text" />
    <Parameter Name="AdminUsuarioID" Parameter="adminUsuarioID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_GASTO_LISTAR_POR_GRUPO" Method="SP_GASTO_LISTAR_POR_GRUPO">
    <Parameter Name="GrupoID" Parameter="grupoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UsuarioID" Parameter="usuarioID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FechaInicio" Parameter="fechaInicio" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="FechaFin" Parameter="fechaFin" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <ElementType Name="SP_GASTO_LISTAR_POR_GRUPOResult">
      <Column Name="GastoID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TransaccionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GrupoID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UsuarioID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NombreUsuario" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Monto" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="Estado" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Fecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_GRUPO_ELIMINAR" Method="SP_GRUPO_ELIMINAR">
    <Parameter Name="GrupoID" Parameter="grupoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="AdminUsuarioID" Parameter="adminUsuarioID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_GRUPO_OBTENER_DETALLES" Method="SP_GRUPO_OBTENER_DETALLES">
    <Parameter Name="GrupoID" Parameter="grupoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UsuarioID" Parameter="usuarioID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <ElementType Name="SP_GRUPO_OBTENER_DETALLESResult">
      <Column Name="GrupoID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="FechaCreacion" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreadoPorUsuarioID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="FechaActualizacion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UsuarioID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NombreUsuario" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Rol" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="FechaUnion" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_INVALIDAR_CODIGO_RECUPERACION" Method="SP_INVALIDAR_CODIGO_RECUPERACION">
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="ErrorID" Parameter="errorID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ErrorMsg" Parameter="errorMsg" Type="System.String" DbType="VarChar(255)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_ACTUALIZAR_CODIGO_RECUPERACION" Method="SP_ACTUALIZAR_CODIGO_RECUPERACION">
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="CodigoVerificacion" Parameter="codigoVerificacion" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="FechaExpiracion" Parameter="fechaExpiracion" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="ErrorID" Parameter="errorID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ErrorMsg" Parameter="errorMsg" Type="System.String" DbType="VarChar(255)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
</Database>